import type { LanguageStats, RepoRef, Stats } from './types';

export type ExportFormat = 'markdown' | 'json' | 'csv';

export interface ExportContext {
  owner: string;
  repo: string;
  ref: RepoRef;
  stats: Stats;
  /** Optional flag to add a "(filtered)" suffix in the heading. */
  filtered?: boolean;
}

const TOOL_URL = 'https://github.com/Poseidon-fan/line-pulse';

function refLabel(ref: RepoRef): string {
  const display = ref.type === 'commit' ? ref.name.slice(0, 7) : ref.name;
  return `${ref.type}: ${display}`;
}

function pct(value: number, total: number): string {
  if (total <= 0) return '0.0%';
  return `${((value / total) * 100).toFixed(1)}%`;
}

function fmt(n: number): string {
  return n.toLocaleString('en-US');
}

function escapeMarkdownTableCell(input: string): string {
  return input.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/**
 * Markdown export — designed to be readable both rendered (issues, READMEs)
 * and as plain text. Uses a stat block + a per-language table.
 */
export function toMarkdown(ctx: ExportContext): string {
  const { owner, repo, ref, stats, filtered } = ctx;
  const heading = filtered
    ? `# ${owner}/${repo} (filtered) \`${refLabel(ref)}\``
    : `# ${owner}/${repo} \`${refLabel(ref)}\``;

  const summary = [
    `**${fmt(stats.totalLines)}** lines · **${fmt(stats.files)}** files · **${stats.languages.length}** languages`,
    '',
    `- Code: ${fmt(stats.totalCode)} (${pct(stats.totalCode, stats.totalLines)})`,
    `- Comments: ${fmt(stats.totalComments)} (${pct(stats.totalComments, stats.totalLines)})`,
    `- Blanks: ${fmt(stats.totalBlanks)} (${pct(stats.totalBlanks, stats.totalLines)})`,
  ].join('\n');

  const tableHeader = [
    '| Language | Files | Code | Comments | Blanks | % of code |',
    '|---|---:|---:|---:|---:|---:|',
  ];
  const tableRows = stats.languages.map((lang: LanguageStats) => {
    const cells = [
      escapeMarkdownTableCell(lang.name),
      fmt(lang.files),
      fmt(lang.code),
      fmt(lang.comments),
      fmt(lang.blanks),
      pct(lang.code, stats.totalCode),
    ];
    return `| ${cells.join(' | ')} |`;
  });

  const footer = `_Generated by [Line Pulse](${TOOL_URL}) on ${new Date().toISOString().slice(0, 10)}_`;

  return [heading, '', summary, '', ...tableHeader, ...tableRows, '', footer, ''].join('\n');
}

/** JSON export — full structured dump for programmatic use. */
export function toJSON(ctx: ExportContext): string {
  const payload = {
    repository: `${ctx.owner}/${ctx.repo}`,
    ref: ctx.ref,
    filtered: ctx.filtered ?? false,
    generatedAt: new Date().toISOString(),
    summary: {
      files: ctx.stats.files,
      totalLines: ctx.stats.totalLines,
      totalCode: ctx.stats.totalCode,
      totalComments: ctx.stats.totalComments,
      totalBlanks: ctx.stats.totalBlanks,
    },
    languages: ctx.stats.languages.map((l) => ({
      name: l.name,
      color: l.color,
      files: l.files,
      code: l.code,
      comments: l.comments,
      blanks: l.blanks,
      lines: l.lines,
    })),
  };
  return JSON.stringify(payload, null, 2);
}

function escapeCSVCell(input: string): string {
  if (/[",\r\n]/.test(input)) {
    return `"${input.replace(/"/g, '""')}"`;
  }
  return input;
}

/** CSV export — one row per language, suitable for Excel / sheets. */
export function toCSV(ctx: ExportContext): string {
  const headers = ['Language', 'Files', 'Code', 'Comments', 'Blanks', 'Lines', 'PercentOfCode'];
  const rows = ctx.stats.languages.map((l) => [
    escapeCSVCell(l.name),
    l.files.toString(),
    l.code.toString(),
    l.comments.toString(),
    l.blanks.toString(),
    l.lines.toString(),
    pct(l.code, ctx.stats.totalCode),
  ]);
  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n') + '\n';
}

export function exportToString(ctx: ExportContext, format: ExportFormat): string {
  switch (format) {
    case 'markdown': return toMarkdown(ctx);
    case 'json': return toJSON(ctx);
    case 'csv': return toCSV(ctx);
  }
}

const MIME: Record<ExportFormat, string> = {
  markdown: 'text/markdown',
  json: 'application/json',
  csv: 'text/csv',
};

const EXT: Record<ExportFormat, string> = {
  markdown: 'md',
  json: 'json',
  csv: 'csv',
};

export function buildFilename(ctx: ExportContext, format: ExportFormat): string {
  const safeRef = ctx.ref.name.replace(/[^a-zA-Z0-9._-]/g, '-').slice(0, 40);
  const suffix = ctx.filtered ? '-filtered' : '';
  return `${ctx.owner}-${ctx.repo}-${safeRef}${suffix}.${EXT[format]}`;
}

/**
 * Trigger a browser download of the exported content. Caller is responsible
 * for revoking the object URL is unnecessary here — we revoke after the
 * synchronous click so memory is freed.
 */
export function downloadExport(ctx: ExportContext, format: ExportFormat): void {
  const content = exportToString(ctx, format);
  const blob = new Blob([content], { type: `${MIME[format]};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  try {
    const a = document.createElement('a');
    a.href = url;
    a.download = buildFilename(ctx, format);
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    a.remove();
  } finally {
    // Defer slightly so the click has time to start the download before
    // the URL is revoked. 1s is comfortably above the spec-required tick.
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
}

/**
 * Copy the rendered string to the clipboard. Returns true on success. Falls
 * back to a `<textarea>` + `execCommand('copy')` route for browsers that
 * still don't expose `navigator.clipboard` to extension contexts.
 */
export async function copyExportToClipboard(
  ctx: ExportContext,
  format: ExportFormat,
): Promise<boolean> {
  const text = exportToString(ctx, format);
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    // fall through to legacy path
  }

  try {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand('copy');
    ta.remove();
    return ok;
  } catch {
    return false;
  }
}
